### ISSUE TITLE
Ethernet

### ISSUE THREAD

**Issue by a2800276** [67P/camp2015#2]
Maybe someone can organize some cat5 cable and a switch to be able to fully utilize the bandwidth...
I can bring some cables and a shitty desktop switch, but we should at least organize some longer cables to hook up to a datenklo.

**Comment by skddc** [comment]
We can bring another shitty desktop switch and some short cables. ;)

**Comment by a2800276** [comment]
Ok, so we may need to buy a large spool in case noone has one.

**Comment by skddc** [comment]
Added to https://ethercalc.org/rsgxp5exvt

**Comment by a2800276** [comment]
we bought 100 m of cat.5 cable, so we have one uplink.  Of course a fallback would be great. And in case anyone wants gigabit ethernet, they'd need to provide cat.6 cables and switch...

**Comment by skddc** [comment]
We're bringing gigabit cables and switch, so a gigabit uplink would be good, of course.

Do we know the distance to cover roughly?

**Comment by a2800276** [comment]
"The maximum line-of-sight distance to the next Datenklo will be approximately 50 meters. Cables will not be provided. A length of 50 meters is recommended. If that is insufficient, you will find someone within this range who has a switch and can plug you in. But bringing 60 or 75 meters won't hurt if you want to be sure."
https://events.ccc.de/camp/2015/wiki/Static:Network

**Comment by a2800276** [comment]
You can get a 100m of cat.6, e.g. at amazon (http://www.amazon.de/Wentronic-CAT6-Netzwerkkabel-geflechtgeschirmt-100m/dp/B003KR2P80/ref=sr_1_2?ie=UTF8&qid=1438177617&sr=8-2&keywords=cat6+100) for ~30€

We have crimping tools, but you'd need to get some cat.6 rj45 plugs as well.

In general, I expect most people in the village will be using the wireless, I doubt we'd need more than 100Mbit, but having a backup cable would probably be a good idea anyway and if you have gigabit switching equipment, cat.6 is not much more expensive anyway.

**Comment by skddc** [comment]
I think cat 5e is enough for 1 Gb/s. Will check the Amazones.
